### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by markusdregi** [equinor/sunbeam#95]
In #94 (and in #93) the new _ErrorGuard_ in _OPM-common_ was utilized in _Sunbeam_ to adapt to the changes in _OPM-common_. Currently, we do nothing with the errors presented by the _ErrorGuard_ and one should evaluate whether this the correct approach and even more so, how _Sunbeam_ can present users with a consistent experience with respect to errors while parsing.

**Comment by joakim-hove** [comment]
The errorguard collects errors which "should" have invoked an exception, so do nothing is in my opinion not a good choice.

**Comment by markusdregi** [comment]
Sounds valid. Could you explain the interplay between the `ParseContext` together with its `PARSE_UNKNOWN_KEYWORD` etc, and the `ErrorGuard`? Also, what used to be the behavior of _OPM-Common_ in situations where the `ErrorGuard` kicks in before the `ErrorGuard` was introduced?

**Comment by joakim-hove** [comment]
The `ParseContext` class has a list of "known errors" - they are listed [here](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/Parser/ParseContext.hpp#L126). When an error is encountered one of the actions listed [here](https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/Parser/InputErrorAction.hpp) is invoked.

The purpose of the `ErrorGuard` is to enable the following two goals:
1. Be able to to parse in the strictest mode - i.e. all errors should be reported.
2. Continue parsing for *as long as possible* - so that as many errors as possible are collected and can be presented to the user, instead of one-error-at-a-time.

> Also, what used to be the behavior of OPM-Common in situations where the ErrorGuard kicks in before the ErrorGuard was introduced?

The `ErrorGuard` *only* kicks in when an error is configured to be treated with the `DELAYED_EXIT1` behavior, currently no errors are configured to use that behavior in the the default setup.

> Also, what used to be the behavior of OPM-Common in situations where the ErrorGuard kicks in before the ErrorGuard was introduced?

That depends on the configured behavior - if the user had not requested anything special you would get the default behavior, which is a mix of `WARN` and `THROW_EXCEPTION` - with a strong bias towards `THROW_EXCEPTION`. If the  user had requested a specific behavior that will be unchanged after the introduction of `ErrorGuard`. 

So all in all the end-user visible changes after the introduction of the `ErrorGuard` are quite limited:

1. The user has got a new error handling mode `DELAYED_EXIT1` which she can explicitly opt-in to.
2. *Iff* at some point in the future the `DELAYED_EXIT1` error mode is used in the default `ParseContext` configuration that will affect the error reporting.

**Comment by markusdregi** [comment]
@joakim-hove Thank you for the extensive summary. My conclusion then is that that we should raise an exception.

**Comment by markusdregi** [comment]
The development of Sunbeam stopped a long time back. The development of the Python bindings are continued in [opm-common](https://github.com/OPM/opm-common) and our recommendation is to use these. Closing all issues.
